name: medicinal_plant_id
description: Offline medicinal plant identifier localized in Arabic.
version: 1.0.0+1
environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Image picker for camera/gallery
  image_picker: ^0.8.7+3

  # TensorFlow Lite (inference)
  tflite_flutter: ^0.9.1
  tflite_flutter_helper: ^0.3.0

  # For RTL / localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

  # JSON parsing is part of dart:convert (no external package needed)

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/model.tflite
    - assets/labels.txt
    - assets/plants_ar.json
